---
# tasks file for roles/nginx

#The next task  only if the target node is  Amazon linux AMI
- name: Enable Nginx repository on Amazon Linux
  command: amazon-linux-extras enable nginx1
  become: true

- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Configure Nginx for vProfile app
  template:
    src: vproapp.conf.j2
    dest: /etc/nginx/conf.d/vproapp.conf

- name: Remove default Nginx configuration
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
#we should define hosts file because we use host names not ip in configuration files 
- name: Configure /etc/hosts
  copy:
    content: |
      127.0.0.1 localhost
      ::1       localhost
      16.171.26.127 db01
      13.60.221.75 mc01
      13.60.221.195 app01
      13.48.25.213 web01
      13.53.168.29 rmq01
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'

- name: Restart and enable Nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

